[package]
name = "qos_p256"
version = "0.1.0"
edition = "2021"

[dependencies]
qos_hex = { path = "../qos_hex" }

sha2 = "0.10.6"
p256 = { version = "0.11.1", features = ["ecdh"] }
rand_core = "0.6.3"
rand = "0.8.5"
aes-gcm = "0.10.1"
borsh = { version = "0.9" }
