[package]
name = "qos_p256"
version = "0.1.0"
edition = "2021"

[dependencies]
qos_hex = { path = "../qos_hex" }

p256 = { version = "0.11.1", features = ["ecdh"] }
aes = "0.7.5"
block-modes = "0.8.1"
rand_core = "0.6.3"
rand = "0.8.5"
