[package]
name = "qos_host"
version = "0.1.0"
edition = "2021"

[dependencies]
qos_core = { path = "../qos_core", default-features = false }

# Third party
axum = { version = "=0.5.16", features = ["http1"], default-features = false }
tokio = { version = "=1.22.0", features = ["macros", "rt-multi-thread"], default-features = false }
borsh = { version = "0.9" }

[features]
vm = ["qos_core/vm"]
