[package]
name = "qos_core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qos_crypto = { path = "../qos_crypto" }
qos_hex = { path = "../qos_hex", features = ["serde"] }
qos_p256 = { path = "../qos_p256" }
qos_nsm = { path = "../qos_nsm", default-features = false }

nix = { version = "0.26", features = ["socket"], default-features = false }
libc = "=0.2.148"
borsh = { version = "1.0", features = ["std", "derive"] , default-features = false}

# For AWS Nitro
aws-nitro-enclaves-nsm-api = { version = "0.3", default-features = false }

serde_bytes = { version = "0.11", default-features = false }
serde = { version = "1", features = ["derive"], default-features = false }

hickory-resolver = { version = "0.24.1", features = ["tokio-runtime"], default-features = false, optional = true}
rand = { version = "0.8.5", default-features = false, optional = true }
[dev-dependencies]
qos_test_primitives = { path = "../qos_test_primitives" }
qos_p256 = { path = "../qos_p256", features = ["mock"] }
qos_nsm = { path = "../qos_nsm", features = ["mock"], default-features = false }
rustls = { version = "0.23.5" }
webpki-roots = { version = "0.26.1" }

[features]
default = ["remote_connection"]
# Support for VSOCK
vm = []
# Never use in production - support for mock NSM
mock = ["qos_nsm/mock"]
# Support for remote connection
remote_connection = ["hickory-resolver", "rand"]
