[package]
name = "qos-test"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
qos-core = { path = "../qos-core" }
qos-host = { path = "../qos-host" }
ureq = { version = "2.4", default-features = false }
tokio = { version = "1.18", features = ["macros", "rt-multi-thread"], default-features = false }