[package]
name = "qos-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
qos-core = { path = "../qos-core" }
qos-host = { path = "../qos-host" }
ureq = "2.4"
futures = "0.3"
tokio = { version = "1.18", features = ["full"], default-features = false }