[workspace]
members = [
  "qos-client",
  "qos-core",
  "qos-crypto",
  "qos-host",
  "qos-test",
  "pivot-test-bin"
]

# [dependencies]
# nix = { version = "0.24.1", features = ["socket"] }

# [dev-dependencies]
# async-std = { version = "1.11.0", features = ["attributes"] }

# [features]
# default=["local"]
# local = []
# vm = []