[package]
name = "qos_crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
openssl = "0.10.40"
borsh = { version = "0.9" }
