[package]
name = "sample-app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qos-core = { path = "../qos-core", default-features = false }
qos-crypto = { path = "../qos-crypto", default-features = false }

borsh = { version = "0.9" }
