[package]
name = "qos_net"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qos_core = { path = "../qos_core", default-features = false }

borsh = { version = "0.10" }
serde = { version = "1", features = ["derive"], default-features = false }
hickory-resolver = { version = "0.24.1", features = ["tokio-runtime"], default-features = false, optional = true}
rand = { version = "0.8.5", default-features = false, optional = true }

[dev-dependencies]
qos_test_primitives = { path = "../qos_test_primitives" }
rustls = { version = "0.23.5" }
webpki-roots = { version = "0.26.1" }

[features]
default = ["proxy"] # keep this as a default feature ensures we lint by default
proxy = ["rand", "hickory-resolver"]
