[workspace]
members = [
  "integration",
  "qos_attest",
  "qos_client",
  "qos_core",
  "qos_crypto",
  "qos_host",
  "qos_hex",
  "qos_aws",
  "qos_system",
  "sample_app",
  "qos_test_primitives",
  "qos_p256"
]
exclude = ["init"]
# We need this to avoid issues with the mock feature uinintentionally being
# enabled just because some tests need it.
# https://nickb.dev/blog/cargo-workspace-and-the-feature-unification-pitfall/
resolver = "2"
