edition = "2021"

# Tabs
hard_tabs = true
tab_spaces = 4

# Line wrapping
use_small_heuristics = "Max"
max_width = 80
# Not a stable feature yet, can't use consistently on StageX builds
# wrap_comments = true

# Imports
reorder_imports = true
# Not a stable feature yet, can't use consistently on StageX builds
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"

# Random
use_field_init_shorthand = true
newline_style = "Unix"
