edition = "2021"

# Tabs
hard_tabs = true
tab_spaces = 4

# Line wrapping
use_small_heuristics = "Max"
max_width = 80

# Imports
reorder_imports = true

# Random
use_field_init_shorthand = true
newline_style = "Unix"

# These lints are not available on stable Rust toolchains, hence can't be used on StageX builds.
# TODO: consider re-enabling them when they've made their way to stable rustfmt
# wrap_comments = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
