[package]
name = "qos-core"
version = "0.1.0"
edition = "2021"

[dependencies]
qos-crypto = { path = "../qos-crypto" }

nix = { version = "0.24.1", features = ["socket"], default-features = false }
aws-nitro-enclaves-nsm-api = { version = "0.2.1", default-features = false }

[features]
default=["local"]
local = []
vm = []
