[package]
name = "qos-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.24.1", features = ["socket"], default-features = false }

[features]
default=["local"]
local = []
vm = []
