[package]
name = "qos-core"
version = "0.1.0"
edition = "2021"

[dependencies]
qos-crypto = { path = "../qos-crypto" }
nix = { version = "0.24.1", features = ["socket"], default-features = false }
openssl = "0.10.40"

# For AWS Nitro
aws-nitro-enclaves-nsm-api = { version = "0.2.1", default-features = false }
serde = "1.0"
serde_cbor = "0.11"
serde_bytes = "0.11"

[features]
default=["local"]
local = []
vm = []
