on: [pull_request]

name: PR

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run tests
        run: make test

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run formatting
        run: make format

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run linting
        run: make lint

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run doc generation
        run: make docs
